---
name: performabot
version: 0.1.0
github: saschagrunert/performabot
license: MIT
author: Sascha Grunert
maintainer: mail@saschagrunert.de
copyright: 2019 Sascha Grunert

extra-source-files:
  - README.md

dependencies:
  - base

flags:
  static:
    default: false
    description: Build static binaries
    manual: false

ghc-options:
  - -Werror
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-implicit-prelude
  - -Wno-missed-specialisations
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-unsafe

default-extensions:
  - GADTs
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - OverloadedStrings
  - QuasiQuotes
  - TemplateHaskell
  - TypeFamilies

executables:
  performabot:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    dependencies:
      - hslogger
      - lens
      - performabot
      - optparse-applicative

library:
  source-dirs: src
  dependencies:
    - ansi-terminal
    - bytestring
    - github
    - hslogger
    - lens
    - megaparsec
    - persistent
    - persistent-sqlite
    - persistent-template
    - regex-compat
    - text
    - time
    - vector
  when:
    - condition: flag(static)
      cc-options: -static -fPIC
      ld-options: -static -fPIC

tests:
  performabot-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    dependencies:
      - lens
      - megaparsec
      - performabot
      - tasty
      - tasty-hspec
      - tasty-quickcheck
      - time
