---
version: 2.1

executors:
  docker:
    docker:
      - image: &image nixos/nix

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - lint

prepare-env: &prepare-env
  run:
    name: Install dependencies
    command: |
      apk add -y make

jobs:
  build:
    executor: docker
    steps:
      - <<: *prepare-env
      - checkout
      - run:
          name: build
          command: make
      - store_artifacts:
          path: result/bin/performabot

  lint:
    executor: docker
    steps:
      - <<: *prepare-env
      - checkout
      - run:
          name: lint
          command: make lint
