#!/usr/bin/env bash
set -euo pipefail

if [ ! -x "$1" ]; then
    echo "File is not executable"
    exit 1
fi

if ! file "$1" | grep "statically linked" | grep -q stripped; then
    echo "Binary is not statically linked and stripped"
    exit 1
fi
