---
stanzas:
  - type: performabot
    exec: ../dist/bin/performabot
    args: []
    hosts:
      - www.hostname.com
    requires-secure: false

  - type: static-files
    hosts:
      - static.hostname.com
    root: ../static

  - type: redirect
    hosts:
      - hostname.com
    actions:
      - host: www.hostname.com
